### ISSUE TITLE
Use roles

### ISSUE THREAD

**Issue by Kimi450** [Kimi450/ubuntu-server#17]
Something like the below might be okay? 

https://github.com/geerlingguy/ansible-role-docker 

```
    - name: Install Docker
      when: install.docker
      include_role:
        name: geerlingguy.docker
        apply:
          become: True
      vars:
        docker_edition: "ce"
        docker_users:
          - "{{ ansible_user }}"
```
